const actionTypes = {
    LOGIN: 'LOGIN',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAIL: 'LOGIN_FAIL',
    LOGOUT: 'LOGOUT',
    GET_POST : 'GET_POST',
    GET_OUTSTANDING: 'GET_OUTSTANDING',
    GET_POST_LIMIT : 'GET_POST_LIMIT',
    GET_POST_ADMIN : 'GET_POST_ADMIN',
    GET_CATEGORIES : 'GET_CATEGORIES ',
    GET_PRICES : 'GET_PRICES ',
    GET_AREAS : 'GET_AREAS ',
    GET_NEW_POSTS : 'GET_NEW_POSTS ',
    EDIT_DATA : 'EDIT_DATA ',
    RESET_DATAEDIT : 'RESET_DATAEDIT ',
    GET_PROVINCES : 'GET_PROVINCES ',

    // user
    GET_CURRENT : 'GET_CURRENT'
}

export default actionTypes